{{- if .Values.abacusConfig.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "abacusConfig.serviceAccountName" . }}
  labels:
    {{- include "abacusConfig.labels" . | nindent 4 }}
  {{- with .Values.abacusConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
