apiVersion: v1
kind: Service
metadata:
  name: {{ include "abacusPortal.fullname" . }}
  labels:
    {{- include "abacusPortal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.abacusPortal.service.type }}
  ports:
    - port: {{ .Values.abacusPortal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "abacusPortal.selectorLabels" . | nindent 4 }}
