{{- if .Values.abacusPortal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "abacusPortal.serviceAccountName" . }}
  labels:
    {{- include "abacusPortal.labels" . | nindent 4 }}
  {{- with .Values.abacusPortal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
