apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
spec:
  schedule: {{ .Values.cronExpression }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            dapr.io/enabled: "true"
            dapr.io/app-id: "{{ .Values.dapr.appId }}-{{ randAlphaNum 10 | lower }}"
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "cronjob.serviceAccountName" . }}
          containers:
          - name: cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - {{ .Values.image.entrypoint }} ; apt-get update; apt-get -y install curl && curl -X POST localhost:3500/v1.0/shutdown
            envFrom:
            - configMapRef:
                name: infiniteabacus-config
            - configMapRef:
                name: abacusflow-config            
          restartPolicy: {{ .Values.restartPolicy }}