apiVersion: v1
kind: Service
metadata:
  name: {{ include "abacus.fullname" . }}
  labels:
    {{- include "abacus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.abacus.service.type }}
  ports:
    - port: {{ .Values.abacus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "abacus.selectorLabels" . | nindent 4 }}
