{{- if .Values.abacus.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "abacus.serviceAccountName" . }}
  labels:
    {{- include "abacus.labels" . | nindent 4 }}
  {{- with .Values.abacus.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
